# Generated by Django 4.0.4 on 2022-04-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0009_students_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='plf_no',
            field=models.CharField(max_length=10),
        ),
    ]
