# Generated by Django 4.0.4 on 2022-04-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0010_alter_students_plf_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password2',
        ),
    ]
