# Generated by Django 4.0.4 on 2022-05-03 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0011_rename_password1_students_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='dob',
            field=models.CharField(max_length=10),
        ),
    ]
