# Generated by Django 4.0.4 on 2022-05-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0016_alter_students_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
