# Generated by Django 4.0.4 on 2022-05-11 15:03

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0022_alter_students_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='pics'), upload_to=''),
        ),
    ]
