# Generated by Django 4.0.4 on 2022-05-11 15:13

import distutils.command.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0023_alter_students_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='img',
            field=models.ImageField(upload_to='', verbose_name=distutils.command.upload.upload),
        ),
    ]
