# Generated by Django 4.0.4 on 2022-05-17 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0030_alter_students_address_alter_students_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='plf_no',
        ),
    ]
