# Generated by Django 4.0.4 on 2022-05-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0031_remove_students_plf_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='room_no',
            field=models.CharField(blank=b'I01\n', default=None, max_length=20),
        ),
    ]
