# Generated by Django 4.0.4 on 2022-05-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sailor', '0033_complaints'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaints',
            old_name='address',
            new_name='desc',
        ),
    ]
